language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
env:
  global:
  - S3_BUCKET=stereo3d.london
  - secure: IEN64wT+TuFQTPESLEiR81EJBDNiFx3c6+llua/uq/uQDCskZv6z1/RfQ3Ds3tEOwu0sO7dz8RymzG4nRdKcn9E2zLTFW6Qp8tlpEnk79BK1W30IDIq79/ZmWjgwItRGRdv+uNSGA4yV7hXMZru4rHfHQikW5fzCAREf3K6SOHY=
  - secure: Klr4PtR/PqS4t3dMG4GEoBL6kcufuiSoHTjeWrpydUeskF2coAj2/1u6fNJa5O5Om1phOm6vCMbk7r5vgFVZljJ31XVHJcvYoWcGo18jO9x6Kh30zB4Ae1/jyqLgyXv3j8Lmy19+jaiQeigVMIX0eLCjync4YV9VQ7j8gNcORG4=
  - secure: MM9okAszUTZsR1wCsXdbgHxnzBBr671yA9UhjkXIYGCdkomtl+Z2w6EWViRJuVGk7TfjS3g+9FLtu+dmme/4FurBL9tLZXsdGD0VbPHZ+HGglfjCSutqXTqmOODZ441WNm51YOpxxEfJu9SPRVA5+26LoG2XU3Ggqv06XnOiLTs=
script:
- gulp
deploy:
  provider: s3
  bucket: stereo3d.london
  skip_cleanup: true
  local-dir: out
  endpoint: alexsavin.me.s3-website-eu-west-1.amazonaws.com
  region: eu-west-1
  access_key_id:
    secure: H1ht8YckYuuDsroCPWPzm6LqRCKOmuwlTMWckuqd3ydPyLqRr732ybVIxlwgXDzCIE302jzTMeccyE/+pfhrSwy3K/UrptyXhLLGLQBLDnL3pTsTgdz03AG1AhUhtap/zEX6Ek81WOZKQwO5MbgOAsplo+qbsyByHn6Bgn2hrUw=
  secret_access_key:
    secure: cCvPHas8TVNLPpY1w13vTytU5A04gjC6FQyQmccW1mGNOvxnVLb6+YRELlT9QB5XS1xUHPiNqmn4XqduyBbV1ib/30h6w6TAtFNalklGiDJ/jHo6ic8+yVtL0xjbUDbvniaEx7ShI64Y3vPtjlI6Da4xfSC2tEGMa50zTlE+vvk=
